### ISSUE TITLE
请问方便将"init_vec"文件的处理过程开源吗

### ISSUE THREAD

**Issue by IKeepMoving** [thunlp/HNRE#11]

**Comment by Perfec-Yu** [comment]
We will include details about the content in init vectors later. Briefly, CNN initial vectors include word embedding. PCNN init vectors are a bit different as we mentioned in the paper. We applied pretrained CNN weights to initialize PCNN. Since PCNN has 3D_hidden outputs compared with CNN, we repeat the relation classification layer 3 times for the PCNN initial classification layer.
我们随后会在repo里面详细更新一下。如果需要的话，简化的细节可以参考一下上面的英文描述。谢谢。
