### ISSUE TITLE
dataset 

### ISSUE THREAD

**Issue by TimWang666** [thunlp/HNRE#9]
the dataset relesed in your code has 57w sent but your paper writes 52w, please tell me the  reason , the two kinds datasets really have very differrent performance i know

**Comment by THUCSTHanxu13** [comment]
OK, the github project (https://github.com/thunlp/NRE) has released two version dataset in history. The first version is the raw_data in our project and followed by the distantly supervised methods in ACL2017 and EMNLP2017 (https://github.com/tyliupku/soft-label-RE, https://github.com/jxwuyi/AtNRE, https://github.com/JuneFeng/RelationClassification-RL). Because these methods are our baselines, we directly follow their implementation and dataset settings. For data description, we also directly follow their papers.

**Comment by THUCSTHanxu13** [comment]
When we implement the github project OpenNRE (https://github.com/thunlp/OpenNRE) recently. We also find that the released dataset is different from the paper description in the project (https://github.com/thunlp/NRE). Then, the project NRE updated the second version of data.

**Comment by THUCSTHanxu13** [comment]
Because the NYT dataset labels the dataset with the KG Freebase which is not maintained for a long time. There are some instances labelled with the relation "NA". This problem may lead to underestimating the model performance. Hence, some human annotated dataset such as Tacred or FewRel may be more suitable for evaluating model performance.

**Comment by TimWang666** [comment]
It is very nice of you to help me solve my problem.  could you introduce me several datasets fitting for distant supervised relation extraction
